// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYu4i7PP5QKMQWa3pbSGafhPOrtW5AD0',
    appId: '1:549876225843:web:ef9cab3a15e8f128a1d046',
    messagingSenderId: '549876225843',
    projectId: 'phonsample',
    authDomain: 'phonsample.firebaseapp.com',
    databaseURL: 'https://phonsample-default-rtdb.firebaseio.com',
    storageBucket: 'phonsample.appspot.com',
    measurementId: 'G-WQ5ZK1RMLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nWuBiljGvPYjLwFXwFiYYtTY5ixjCrg',
    appId: '1:549876225843:android:04df65680f45cb77a1d046',
    messagingSenderId: '549876225843',
    projectId: 'phonsample',
    databaseURL: 'https://phonsample-default-rtdb.firebaseio.com',
    storageBucket: 'phonsample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FwEEwjYVcU1oE0GLL4qou19CjfC6tWA',
    appId: '1:549876225843:ios:347422ddd89bbd71a1d046',
    messagingSenderId: '549876225843',
    projectId: 'phonsample',
    databaseURL: 'https://phonsample-default-rtdb.firebaseio.com',
    storageBucket: 'phonsample.appspot.com',
    iosClientId: '549876225843-obeq7de45vilj2ff31uafq465bipllsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FwEEwjYVcU1oE0GLL4qou19CjfC6tWA',
    appId: '1:549876225843:ios:347422ddd89bbd71a1d046',
    messagingSenderId: '549876225843',
    projectId: 'phonsample',
    databaseURL: 'https://phonsample-default-rtdb.firebaseio.com',
    storageBucket: 'phonsample.appspot.com',
    iosClientId: '549876225843-obeq7de45vilj2ff31uafq465bipllsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppExample',
  );
}
